--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CLADevs/Minion
branches:
- master
projects:
  Minion:
    path: ""
    libs:
      - src: muqsit/invMenu/InvMenu
        version: ^4.5.0
...
